### ISSUE TITLE
Centralized monitoring

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-experimental-microservices#11]
This is linked to #5 

We need to centralize the Dropwizard Metrics monitoring for all microservices.

Code for this is already written in the MetricsConfiguration class, and this data could be send to Graphite or Spark.
- We should check whether Graphite is the good choice vs Grafana
- See how we can generate a Graphite configuration (maybe a Docker build?) that could aggregate all metrics, and maybe have some alerting and dashboards provided out-of-the-box

**Comment by jdubois** [comment]
Done

**Comment by cbornet** [comment]
You mean that we have a graphite conf with alerting and dashboards (would be too amazing to be true) or is it just the metrics aggregation part ?

**Comment by jdubois** [comment]
We have an ELK server getting all the logs
For Graphite I need to ask @PierreBesson but he also has something working

I'm mostly closing those as I'm going to close this repo and so I'm moving everything to the generator

**Comment by PierreBesson** [comment]
I have something working but it is not completely satisfying as it is not an official docker image. Basically I just played with [kamon-io/docker-grafana-graphite](https://github.com/kamon-io/docker-grafana-graphite) and it is able to receive dropwizard metrics from a classic JHipster app through the graphite reporter.

**Comment by cbornet** [comment]
I've also started playing with the kamon image and it really looks like what we should provide as base  for production monitoring. I don't know if we should derive an image from kamon or create our own. What we should provide is all the metrics from the webapp but in graphs form. Maybe this could be hosted by @pascalgrimaud 's docker module ?

**Comment by cbornet** [comment]
@PierreBesson do you have some graphana conf to start with ?

**Comment by PierreBesson** [comment]
If you mean custom dashboards, not really. But the following [Kamon tutorial](https://dzone.com/articles/create-amazing-stat-dashboards-for-your-app-locall) is a good read to get started.
However I have played a little with many graphite and graphana docker images.
I liked the Kamon images initially but I didn't like that they added their own advertisement in it.
Currently I use the following compose file. Not sure if it works completely...

```
graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
grafana:
    image: grafana/grafana
    restart: always
    ports:
        - "3000:3000"
    volumes:
        - "./metrics-monitoring/data/grafana:/var/lib/grafana"
    links:
        - graphite
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=password
```
